### ISSUE TITLE
Regression in Kotlin 2.0.21 support?

### ISSUE THREAD

**Issue by jrodbx** [drewhamilton/Poko#451]
We're seeing the following issue on the paparazzi repo when attempting to bump to 0.18.1:

```
e: java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.ir.expressions.impl.IrWhenImpl org.jetbrains.kotlin.ir.builders.ExpressionHelpersKt.irIfThenReturnTrue(org.jetbrains.kotlin.ir.builders.IrBuilderWithScope, org.jetbrains.kotlin.ir.expressions.IrExpression)'
	at dev.drewhamilton.poko.ir.EqualsGenerationKt.generateEqualsMethodBody(equalsGeneration.kt:62)
	at dev.drewhamilton.poko.ir.PokoMembersTransformer.visitFunctionNew(PokoMembersTransformer.kt:47)
	at org.jetbrains.kotlin.backend.common.IrElementTransformerVoidWithContext.visitFunction(IrElementTransformerVoidWithContext.kt:83)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:128)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:131)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:19)
	at org.jetbrains.kotlin.ir.declarations.IrSimpleFunction.accept(IrSimpleFunction.kt:39)
	at org.jetbrains.kotlin.ir.IrElementBase.transform(IrElementBase.kt:33)
	at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
	at org.jetbrains.kotlin.ir.declarations.IrClass.transformChildren(IrClass.kt:82)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitDeclaration(IrElementTransformerVoid.kt:40)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitClass(IrElementTransformerVoid.kt:54)
	at org.jetbrains.kotlin.backend.common.IrElementTransformerVoidWithContext.visitClassNew(IrElementTransformerVoidWithContext.kt:126)
	at org.jetbrains.kotlin.backend.common.IrElementTransformerVoidWithContext.visitClass(IrElementTransformerVoidWithContext.kt:62)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitClass(IrElementTransformerVoid.kt:[57](https://github.com/cashapp/paparazzi/actions/runs/12326572308/job/34407534118?pr=1747#step:5:58))
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitClass(IrElementTransformerVoid.kt:19)
	at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:72)
...
```

which reads similar to https://github.com/drewhamilton/Poko/issues/363.

However, 

1) We've been on Kotlin 2.0.21 for [about a month](https://github.com/cashapp/paparazzi/commit/d6e5e21d90c8e727dcd67dbf813db5ef7b649424) whereas #363 is reported w.r.t. Kotlin 2.0.20.
2) The issue only arises when bumping [from Poko 0.18.0 to 0.18.1](https://github.com/cashapp/paparazzi/pull/1747) [[example failed build log](https://github.com/cashapp/paparazzi/actions/runs/12326572308/job/34407534118?pr=1747)]

**Comment by drewhamilton** [comment]
Poko 0.18.0 officially dropped support for Kotlin 2.0.x, but it still had some internal reflection code that provided partial compatibility which was probably enough for you to get by. I deleted that code in between 0.18.0 and 0.18.1. Technically you should stick with Poko 0.17.2 until you bump to Kotlin 2.1.x (check the table in the readme).
