### ISSUE TITLE
Compiler error: NoSuchMethod Kotlin 1.6.20

### ISSUE THREAD

**Issue by MariusVolkhart** [drewhamilton/Poko#73]
I get the following error when running my gradle build after updating to:
- Kotlin: 1.6.20
- KSP: 1.6.20-1.0.5 and 1.6.20-1.0.4
- Poko: 0.9.0

```java
java.lang.NoSuchMethodError: 'void org.jetbrains.kotlin.ir.declarations.impl.IrValueParameterImpl.<init>(int, int, org.jetbrains.kotlin.ir.declarations.IrDeclarationOrigin, org.jetbrains.kotlin.ir.symbols.IrValueParameterSymbol, org.jetbrains.kotlin.name.Name, int, org.jetbrains.kotlin.ir.types.IrType, org.jetbrains.kotlin.ir.types.IrType, boolean, boolean, boolean, boolean)'
	at dev.drewhamilton.poko.ir.PokoMembersTransformer.mutateWithNewDispatchReceiverParameterForParentClass(PokoMembersTransformer.kt:348)
	at dev.drewhamilton.poko.ir.PokoMembersTransformer.visitFunctionNew(PokoMembersTransformer.kt:411)
	at org.jetbrains.kotlin.backend.common.IrElementTransformerVoidWithContext.visitFunction(IrElementTransformerVoidWithContext.kt:68)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:72)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:73)
```

The code in question is essentially,

```kotlin
public sealed interface Animal {
    public val name: String 
}

@Poko
public class Dog(override val name: String) : Animal
```

**Comment by drewhamilton** [comment]
It seems like that signature should be there unless I'm misreading a subtle signature change. Can you see if 0.10.0-SNAPSHOT changes anything?

**Comment by MariusVolkhart** [comment]
`0.10.0-SNAPSHOT` does indeed resolve the error

**Comment by drewhamilton** [comment]
Great, I'll cut a release of that soon

**Comment by drewhamilton** [comment]
Found the issue: 1.6.20 added a new parameter with a default value to that constructor – so it was source compatible but not binary compatible.

0.10.0 is released!

**Comment by MariusVolkhart** [comment]
Awesome, thanks!
